on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
      
      # add software dependencies here

      # To publish to Netlify, RStudio Connect, or GitHub Pages, uncomment
      # the appropriate block below
      
      # - name: Publish to Netlify (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: netlify
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
      # - name: Publish to RStudio Connect (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: connect
      #     CONNECT_SERVER: enter-the-server-url-here
      #     CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }} 

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Add system libcurl package 
        run: sudo apt-get install -y libcurl4-openssl-dev
        
      - name: Add system harfbuzz package 
        run: sudo apt-get install -y libharfbuzz-dev
        
      - name: Add system fribidi package 
        run: sudo apt-get install -y libfribidi-dev
        
      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: rap-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
          
      - name: Render CKP PDFs
        run: Rscript R/render-reports.R
